// ERROR TYPES
export const GET_ERRORS = "GET_ERRORS";

//AUTH TYPES
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SUCCESS_RESET = "SUCESS_RESET";

// PREDICTIONS TYPES

export const PREDICTIONS_SUCCESS = "PREDICTIONS_SUCCESS";
export const PREDICTIONS_REQUEST = "PREDICTIONS_REQUEST";
export const PREDICTIONS_ERROR = "PREDICTIONS_ERROR";
