// ERROR TYPES
export const GET_ERRORS = "GET_ERRORS";

//AUTH TYPES
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SUCCESS_RESET = "SUCESS_RESET";

// PREDICTIONS TYPES

export const PREDICTIONS_SUCCESS = "PREDICTIONS_SUCCESS";
export const PREDICTIONS_REQUEST = "PREDICTIONS_REQUEST";
export const PREDICTIONS_ERROR = "PREDICTIONS_ERROR";

// INVETORY

export const BATCH_PICTURES_SUCCESS = "BATCH_PICTURES_SUCCESS";
export const BATCH_PICTURES_REQUEST = "BATCH_PICTURES_REQUEST";
export const BATCH_PICTURES_ERROR = "BATCH_PICTURES_ERROR";
